apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-app-stg

resources:
- ../../base

## include this for a large change
# - datadog/helmed.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- hpa-patch.yaml
- keda-patch.yaml

commonLabels:
  environment: stg

namePrefix: stg-
