apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-app-prod

resources:
- ../../base

## include this for a large change
# - ingress-nginx/helmed.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- hpa-patch.yaml
- keda-patch.yaml

commonLabels:
  environment: prod

namePrefix: prod-
